export enum TRPCErrorCode {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  BAD_REQUEST = "BAD_REQUEST",
  UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT",
}

export const SLUG_COOKIE_NAME = "transparify.signup.slug";
